"""Complete restructure with UUIDs

Revision ID: 54838a2d6733
Revises: 
Create Date: 2026-06-08 10:56:40.868579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54838a2d6733'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signalements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('declarant_nom', sa.String(), nullable=False),
    sa.Column('type_signalement', sa.Enum('PERSONNE_DISPARUE', 'ENGIN_VOLE', name='typesignalementenum'), nullable=False),
    sa.Column('declarant_contact', sa.String(), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'VALIDE', 'REJETE', name='statutsignalementenum'), nullable=True),
    sa.Column('date_declaration', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('date_heure', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('adresse_ip', sa.String(), nullable=True),
    sa.Column('utilisateur_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engins_voles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('marque', sa.String(), nullable=False),
    sa.Column('modele', sa.String(), nullable=False),
    sa.Column('couleur', sa.String(), nullable=True),
    sa.Column('type_engin', sa.String(), nullable=False),
    sa.Column('plaque_immatriculation', sa.String(), nullable=False),
    sa.Column('date_vol', sa.Date(), nullable=True),
    sa.Column('statut', sa.Enum('RECHERCHE', 'RETROUVE', 'ARCHIVE', name='statutenginenum'), nullable=True),
    sa.Column('signalement_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['signalement_id'], ['signalements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plaque_immatriculation')
    )
    op.create_table('personnes_disparues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prenoms', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('niveau_gravite', sa.Enum('PAS_GRAVE', 'GRAVE', 'TRES_GRAVE', name='niveaugraviteenum'), nullable=True),
    sa.Column('date_disparition', sa.Date(), nullable=True),
    sa.Column('lieu_disparition', sa.String(), nullable=True),
    sa.Column('vecteur_facial', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('photo', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('signalement_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['signalement_id'], ['signalements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date_heure', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('score_confiance', sa.Float(), nullable=False),
    sa.Column('image_capture', sa.String(), nullable=True),
    sa.Column('localisation', sa.String(), nullable=True),
    sa.Column('type_detection', sa.Enum('PERSONNE', 'ENGIN', name='typedetectionenum'), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('personne_disparue_id', sa.String(), nullable=True),
    sa.Column('engin_vole_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['engin_vole_id'], ['engins_voles.id'], ),
    sa.ForeignKeyConstraint(['personne_disparue_id'], ['personnes_disparues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alertes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('niveau_gravite', sa.Enum('PAS_GRAVE', 'GRAVE', 'TRES_GRAVE', name='graviteenum'), nullable=False),
    sa.Column('type_detection', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('est_lue', sa.Boolean(), nullable=True),
    sa.Column('date_emission', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('detection_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fournisseur_sms', sa.String(), nullable=True),
    sa.Column('fournisseur_email', sa.String(), nullable=True),
    sa.Column('alerte_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alerte_id'], ['alertes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_persons_id'), table_name='persons')
    op.drop_table('persons')
    op.add_column('cameras', sa.Column('nom', sa.String(), nullable=False))
    op.add_column('cameras', sa.Column('type', sa.Enum('IP', 'ESP32', 'MOBILE', name='typecameraenum'), nullable=True))
    op.add_column('cameras', sa.Column('description', sa.String(), nullable=True))
    op.add_column('cameras', sa.Column('localisation', sa.String(), nullable=True))
    op.add_column('cameras', sa.Column('url_flux', sa.String(), nullable=True))
    op.add_column('cameras', sa.Column('est_active', sa.Boolean(), nullable=True))
    op.alter_column('cameras', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_column('cameras', 'rtsp_url')
    op.drop_column('cameras', 'name')
    op.drop_column('cameras', 'status')
    op.drop_column('cameras', 'address')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('cameras', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cameras', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cameras', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('cameras', sa.Column('rtsp_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    op.alter_column('cameras', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('cameras', 'est_active')
    op.drop_column('cameras', 'url_flux')
    op.drop_column('cameras', 'localisation')
    op.drop_column('cameras', 'description')
    op.drop_column('cameras', 'type')
    op.drop_column('cameras', 'nom')
    op.create_table('persons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('height_cm', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('distinctive_signs', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('disappearance_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('gravity_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_ai_ready', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ai_metadata', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('persons_pkey'))
    )
    op.create_index(op.f('ix_persons_id'), 'persons', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('camera_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('captured_photo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gravity_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('alerts_camera_id_fkey')),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('alerts_person_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alerts_pkey'))
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.drop_table('notifications')
    op.drop_table('alertes')
    op.drop_table('detections')
    op.drop_table('personnes_disparues')
    op.drop_table('engins_voles')
    op.drop_table('audits')
    op.drop_table('signalements')
    # ### end Alembic commands ###
